apiVersion: apps/v1
kind: Deployment
metadata:
  name: project4
spec:
  selector:
    matchLabels:
      name: project4
  template:
    metadata:
      labels:
        name: project4
    spec:
      containers:
      - name: project4
        image: udacitycourseqwert/project4:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 200m
      imagePullSecrets:
      - name: project4
