apiVersion: v1
kind: Service
metadata:
  name: project4
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30001
      name: app-nodeport
      protocol: TCP
  selector:
    name: project4